language: python
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev
python:
  - "2.7"
# don't rebuild pocketsphinx for every build
cache: pocketsphinx-python
# command to install dependencies
install:
 - VIRTUALENV_ROOT=${VIRTUAL_ENV} ./dev_setup.sh
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt
# command to run tests
script:
 - pep8 mycroft test
 - ./start-mycroft.sh unittest
env:
 - IS_TRAVIS=true

after_success:
  coveralls
