branches:
  only:
    - master
    - dev

language: python

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath
 - sudo apt-get install -y gcc-4.8 g++-4.8
 - export CC="gcc-4.8"
 - export TMPDIR="/tmp/${TRAVIS_PYTHON_VERSION}"
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# don't rebuild pocketsphinx for every build
cache:
  - pip
  - pocketsphinx-python
# command to install dependencies
install:
 - rm -rf ${TMPDIR}
 - mkdir ${TMPDIR}
 - echo ${TMPDIR}
 - VIRTUALENV_ROOT=${VIRTUAL_ENV} ./dev_setup.sh
# command to run tests
script:
 - pycodestyle mycroft test
 - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
 - ./start-mycroft.sh unittest

after_success:
  coveralls
