branches:
  only:
    - master
    - dev

language: python
dist: xenial

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath
 - sudo apt-get install -y gcc-4.8 g++-4.8
 - export CC="gcc-4.8"
 - export TMPDIR="/tmp/${TRAVIS_PYTHON_VERSION}"
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# don't rebuild pocketsphinx for every build
cache: pocketsphinx-python
# command to install dependencies
install:
 - rm -rf ${TMPDIR}
 - mkdir ${TMPDIR}
 - echo ${TMPDIR}
 - VIRTUALENV_ROOT=${VIRTUAL_ENV} ./dev_setup.sh
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt
# command to run tests
script:
 - pycodestyle mycroft test
 - ./start-mycroft.sh unittest

after_success:
  coveralls
