# This workflow will install Python dependencies, run tests and lint with all supported versions of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Myroft Core CI

on:
  push:
    branches: [ test-github-actions ]
  pull_request:
    branches: [ test-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip packages
      uses: actions/cache@v2
      env:
        cache-name: cache-pypi-modules
      with:
        # pip cache files are stored in `~/.cache/pip` on Linux
         path: ~/.cache/pip
         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('requirements/requirements.txt', 'requirements/tests.txt') }}
         restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-
    - name: Install apt dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev coreutils
        sudo apt-get install -y gcc-4.8 g++-4.8
    - name: Install test dependencies
      run: |
        pip install -r requirements/tests.txt
    - name: Run dev_setup script
      run: |
        export CC="gcc-4.8"
        export CI=true
        export TMPDIR="/tmp/${{ matrix.python-version }}"
        rm -rf ${TMPDIR}
        mkdir ${TMPDIR}
        echo ${TMPDIR}
        if [[ ${{ matrix.python-version }} == 3.9 ]]; then VIRTUALENV_ROOT=${VIRTUAL_ENV} ./dev_setup.sh; fi
        # Skip mimic build for other versions because they should not differ
        if [[ ${{ matrix.python-version }} != 3.9 ]]; then VIRTUALENV_ROOT=${VIRTUAL_ENV} ./dev_setup.sh -sm; fi
    - name: Linting and formatting checks
      run: |
        pycodestyle mycroft test
        flake8 mycroft test --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run the unit tests with pytest
      run: |
        source ${VIRTUALENV_ROOT}/bin/activate
        python3 -m pip install pytest-cov
        pytest test/unittests/ --cov=mycroft --cov-report html
